---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: tests/test_changes/
        files: \.(py|sh|rst|yml|yaml)$
      - id: mixed-line-ending
      - id: trailing-whitespace
        files: \.(py|sh|rst|yml|yaml)$
  - repo: local
    hooks:
      - id: local-biome-check
        name: biome check
        entry: bunx @biomejs/biome check --write --files-ignore-unknown=true --no-errors-on-unmatched --unsafe
        language: system
        types: [text]
        files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?)$"
